package Base;

public class Exception_handling {

	public static void main(String[] args) {
try
{
	
		int c = 1/0;
	

}

catch(ArithmeticException e)
		
{
	System.out.println("exception handled ");

}
	}

}
